### ISSUE TITLE
两点小的调整可以考虑下么

### ISSUE THREAD

**Issue by jing2uo** [zenozeng/electronic-wechat-deb#1]
我也在用sid，想自己打包来着发现你做好啦。多谢~
不过有两个小地方希望能改进下——
1.desktop没有Categories，在菜单里会被放到other，我会把它和chrome，hexchat放一起，加这行：
`Categories=Network;`
2.第三方包一般都会放到/opt，比如sublimetext，虽然放到/usr也不影响使用啦，但总觉得和apt混合到一起不太好的样子，可能每个人习惯不一样~

**Comment by zenozeng** [comment]
@hipkomh Categories 已经加上了。CI 中：https://circleci.com/gh/zenozeng/electronic-wechat-deb/28 。
目录的问题我个人习惯上所有由 dpkg 管理的包会丢在 /usr，不由dpkg管理的会放在 /opt。不过马上要出个门，这个我可能需要晚点查一下文档看看官方推荐的做法。

**Comment by jing2uo** [comment]
嗯嗯，谢谢采纳及回复~：）
我那天表述有点问题哈，dpkg安装的包(划掉)其实是想说不在源里的第三方包，修改了一下。
